### PR TITLE
entrance vs application

### PR DESCRIPTION
**Pull request by rub1e**
just clarified that these are entrance prereqs not application ones - as this is a very common question on the contact form

### CODE REVIEW

**Comment by hdrdavies** [comment]
@rub1e  absolutely right. Thanks for modifying.

**Comment by iteles** [comment]
@rub1e Worth making this mod on the website in the short term too to cut down on emails you have to answer?

**Comment by sofer** [comment]
@iteles yes it is. https://github.com/foundersandcoders/oursite/issues/193.

**Comment by sofer** [comment]
@rub1e are these amendments sufficient? http://www.foundersandcoders.com/academy/

**Comment by rub1e** [comment]
yeah looks fine for now - I'm aiming to do a comprehensive review over the xmas break

Although it might be worth holding off until we have a website working group

**Pull request merged**
